### ISSUE TITLE
Keysight IO Library as VISA backbend

### ISSUE THREAD

**Issue by artwe** [RuixeWolf/node-ni-visa#1]
Can I use Keysight IO Library as VISA backbend？ Have you ever tried it?

**Comment by cvalgoi** [comment]
I have not tried it and wasn't aware of it. But I would guess it will work properly .. Node support is not mentioned directly on the official site by the way.

https://www.keysight.com/us/en/lib/software-detail/computer-software/io-libraries-suite-downloads-2175637.html

________________________________
From: sunxw ***@***.***>
Sent: 07 May 2024 16:02
To: RuixeWolf/node-ni-visa ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RuixeWolf/node-ni-visa] Keysight IO Library as VISA backbend (Issue #1)


Can I use Keysight IO Library as VISA backbend？ Have you ever tried it?

**Comment by RuixeWolf** [comment]
I didn't try it. After install [NI-VISA](https://www.ni.com/en/support/downloads/drivers/download.ni-visa.html) on Windows, VISA DLL files `visa32.dll` or `visa64.dll` will be found in `C:\Windows\System32`, `node-ni-visa` calling them directly. If `visa32.dll` or `visa64.dll` exist in `C:\Windows\System32` after install Keysight IO Library, it may be possible to use them as VISA backend for `node-ni-visa`. Welcome to try it and feedback.
